version: "3"

services:
  go-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SERVER_PORT: 8080
      MONGO_URL: "mongodb://mongodb:27017"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
